[workspace]
members = ["pett_server"]

[profile.release]
# Slower compilation, but better performance of final executable.
# <https://blog.rust-lang.org/2018/02/15/Rust-1.24.html#incremental-compilation>
codegen-units = 1
