[alias]
coverage_clean = ["llvm-cov", "clean", "--workspace"]
coverage = ["llvm-cov", "--no-report", "--output-dir", "./target/coverage", "nextest", "--workspace"]
coverage_merge = 'llvm-cov report --lcov --output-path ./target/coverage/lcov.info'
coverage_open = 'llvm-cov report --open --output-dir ./target/coverage'
