[package]
name = "pett_server"
version = "0.1.2"
description = "Web application with hello world, health, and metadata endpoints"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }
tokio = { version = "1.21.2", features = ["fs", "macros", "rt", "rt-multi-thread"] }
warp = "0.3.3"

[dev-dependencies]
bytes = "1.2.1"
serde_json = "1.0.87"
tempfile = "3.3.0"

[build-dependencies]
git2 = "0.15.0"
