[package]
name = "pett_server"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.2.3"
tokio = { version = "0.2.21", features = ["fs", "macros", "rt-core"] }
