[package]
name = "pett_server"
version = "0.1.1"
description = "Web application with hello world, health, and metadata endpoints"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.111", features = ["derive"] }
tokio = { version = "0.2.21", features = ["fs", "macros", "rt-core"] }
warp = "0.2.3"

[dev-dependencies]
bytes = "0.5.4"
serde_json = "1.0.55"
tempfile = "3.1.0"

[build-dependencies]
git2 = "0.13.6"
